# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0jm_87KjDc7zW_m3Rr9Jgd9TF3OlMVq
"""

# Import necessary libraries
from flask import Flask, render_template, request
import pickle
import numpy as np

# Initialize Flask application
app = Flask(__name__)

# Load the machine learning model from a saved file

import os
import sys
import pickle

# Define the route for the home page
@app.route('/')
def home():
    return render_template('index.html')

# Define the route for the prediction page
@app.route('/predict', methods=['POST'])
def predict():
    # Retrieve the input values from the form
    age = int(request.form['age'])
    gender = int(request.form['gender'])
    family_history = int(request.form['family_history'])
    symptoms = int(request.form['symptoms'])

def main():
  age = getAge()
  weight = getWeight()
  birthMonth = getBirth()
  correct(age,weight,birthMonth)

def getAge():
  age = float(input("Guess the age.\t"))
  return age
def getWeight():
  weight = float(input("Guess the weight.\t"))
  return weight
def getBirth():
  birthMonth = input("Guess the month.\t")
  return birthMonth
def correct(age,weight,birthMonth):
  if age <= 25:
     print ("Congratulations, the age is 25 or less")
  else:
    print ("You did not correctly guess the age")
  if weight <= 128:
    print ("Congratulations, the weight is 128 or more")
  else:
    print ("You did not correctly guess the weight")
  if birthMonth == "April":
    print ("Congratulations, the month is April")
  else:
    print ("You did not correctly guess the month")

main()

import tensorflow as tf
from tensorflow.keras.layers import Dense
from keras.models import Model

# Make a prediction using the machine learning model

from tensorflow.keras.models import Model

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

# Return the prediction as a response

# Run the Flask application
if __name__ == '__main__':
    app.run(debug=True)

